### ISSUE TITLE
Non-contextual replications

### ISSUE THREAD

**Issue by mollyow** [UChicago-pol-methods/banditsCI#14]
In non-contextual setting, can we run simulations one time and check against estimates produced by our package? https://github.com/gsbDBI/adaptive-confidence-intervals/blob/master/experiments/main/simulations.ipynb

Work in progress here: https://github.com/UChicago-pol-methods/adaptive-confidence-intervals/blob/non_contextual_replication/experiments/main/simulations.ipynb

- [x] tiny update to readme for what we need to compare

**Comment by YinghuiZhouu** [comment]
- [ ] Read the papers again, find out what are comparable to the methods `lvdl`... from python code.
- [ ] Tidy the simulation.ipynb code, only include the methods we need, and only save the results we want.
- [ ] Compare the `df_contrast` with ours. Use the experiment data we get from simulation.ipynb, and use our package to calculate

**Comment by YinghuiZhouu** [comment]
| estimator/weighting                                                                                                                                                                         | paper               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                               | In our code? |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------ |
| DR(uniformly-weighting)                                                                                                                                                                     | Off-Policy          | $\hat{Q}^{DR}_T (\pi) := \frac{1}{T} \sum_{t=1}^T \hat{\Gamma}_t(X_t, \pi)$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                               |              |
| improve on the DR estimator(stabilize variance)                                                                                                                                             | Off-Policy          | $\hat{Q}^{NC}_T(\pi) := \frac{\sum_{t=1}^{T} h_t \hat{\Gamma}_t(X_t, \pi)}{\sum_{t=1}^{T} h_s}$, $h_t := \phi \left( \mathbb{E}_w \left[ \frac{\pi^2(X_t; w)}{e_t(X_t; w)} \| H_{t-1} \right] \right)$                                                                                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                               |              |
| contextual-weighting                                                                                                                                                                        | Off-Policy          | $\hat{Q}^{\mathcal{C}}_T (\pi) = \frac{\sum_{t=1}^T h_t(X_t) \hat{\Gamma}_t(X_t, \pi)}{\sum_{t=1}^T h_s(X_t)}$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                                                               |              |
| StableVar: improve on the DR estimator(stabilize variance)                                                                                                                                  | Off-Policy          | $\phi(v) = 1/\sqrt{v}$ yields weights $h_t$ that approximately standardize the terms of $\hat{Q}^{NC}_T$ or $\hat{Q}^{\mathcal{C}}_T (\pi)$. <br>**Non-contextual** variance proxy: $h_t := \phi \left( \mathbb{E}_w \left[ \frac{\pi^2(X_t; w)}{e_t(X_t; w)} \| H_{t-1} \right] \right)$,<br>a feasible approximation in our simulation: $\tilde{h}_t := \phi \left( \frac{1}{t - 1} \sum_{s=1}^{t-1} \sum_w \frac{\pi^2(X_s; w)}{e_t(X_s; w)} \right)$<br>**contextual variance** proxy: $h_t(x) = \phi \left( \sum_w \frac{\pi^2(x, w)}{e_t(x, w)} \right), \quad x \in \mathcal{X}$<br><br> | less eﬀective at reducing variance than MinVar                                                                                                                                                                |              |
| MinVar: improve on the DR estimator(stabilize variance)                                                                                                                                     | Off-Policy          | $\phi(v) = 1/v$ yields weights $h_t$ that approximately minimize the variance of $\hat{Q}^{NC}_T$ or $\hat{Q}^{\mathcal{C}}_T (\pi)$. <br>**Non-contextual** variance proxy: $h_t := \phi \left( \mathbb{E}_w \left[ \frac{\pi^2(X_t; w)}{e_t(X_t; w)} \| H_{t-1} \right] \right)$,<br>a feasible approximation in our simulation: $\tilde{h}_t := \phi \left( \frac{1}{t - 1} \sum_{s=1}^{t-1} \sum_w \frac{\pi^2(X_s; w)}{e_t(X_s; w)} \right)$<br>**contextual variance** proxy: $h_t(x) = \phi \left( \sum_w \frac{\pi^2(x, w)}{e_t(x, w)} \right), \quad x \in \mathcal{X}$<br><br>        | However, our result requires more fragile assumptions on the data generating process and assignment mechanism. Again, we focus on evaluating a ﬁxedarm policy that always assigns a pre-speciﬁed treatment w. |              |
| sample mean naive(normal CI)                                                                                                                                                                | Confidence Interval | $\hat{Q}^{AVG}(w) = \frac{1}{T_w} \sum_{t \leq T} Y_t \mathbb{I}{\{W_t = w\}}, \quad T_w := \sum_{t \leq T} \mathbb{I}{\{W_t = w\}}$<br>In the code: sample_mean_naive<br>                                                                                                                                                                                                                                                                                                                                                                                                                      | biased downward                                                                                                                                                                                               |              |
| Sample mean (Howard et al CI)                                                                                                                                                               | Confidence Interval |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                               |              |
| non-asymptotic confidence intervals for the sample mean, based on the method of time-uniform confidence sequences described in [Howard et al. (2021)](https://arxiv.org/pdf/1810.08240.pdf) | Confidence Interval | In the code: evaluatie_gamma_exponential                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                               |              |
| Unweighted AIPW(uniform)                                                                                                                                                                    | Confidence Interval | $\hat{Q}^{AIPW}_T (w) := \frac{1}{T} \sum_{t=1}^T \hat{\Gamma}^{AIPW}_t (w)$<br><br>"Figures 2 and 4 show that although the AIPW estimator with **uniform weights** (labeled as “unweighted AIPW”) is unbiased (P12)"<br>                                                                                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                               |              |
| Weighted AIPW                                                                                                                                                                               | Confidence Interval | Regression adjusted: $\hat{\Gamma}^{AIPW}_t (w) := \frac{I\{W_t = w\}}{e_t(w)} Y_t + \left( 1 - \frac{I\{W_t = w\}}{e_t(w)} \right) \hat{m}_t(w)$<br>*adaptively-weighted AIPW estimator*:<br><br>$\hat{Q}^{h}_T(w) = \frac{\sum_{t=1}^T h_t(w) \hat{\Gamma}^{AIPW}_t (w)}{\sum_{t=1}^T h_t(w)}$<br>                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                               |              |
| **Constant allocation rate**(lvdl)                                                                                                                                                          | Confidence Interval | "stick-breaking" procedure, $\frac{h_t^2}{e_t} = \left(1 - \sum_{s=1}^{t-1} \frac{h_s^2}{e_s} \right) \lambda_t$, where $\lambda_t$ satisfies $0 \leq \lambda_t < 1$ for all $1 \leq t \leq T - 1$, and $\lambda_T = 1$.<br><br>$\lambda^{const}_t := \frac{1}{T - t + 1}$<br><br>                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                               |              |
| **Two-point allocation rate**                                                                                                                                                               | Confidence Interval | "stick-breaking" procedure, $\frac{h_t^2}{e_t} = \left(1 - \sum_{s=1}^{t-1} \frac{h_s^2}{e_s} \right) \lambda_t$, where $\lambda_t$ satisfies $0 \leq \lambda_t < 1$ for all $1 \leq t \leq T - 1$, and $\lambda_T = 1$.<br><br>$\lambda^{two-point}_t := e_t \frac{1}{T - t + 1} + (1 - e_t) \frac{t - \alpha}{t} \frac{T - \alpha - t}{T - \alpha - 1} \frac{1 - \alpha}{1 - \alpha}$<br>                                                                                                                                                                                                     |                                                                                                                                                                                                               |              |
|                                                                                                                                                                                             |                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                               |              |
